/**
 * The supplier's monthly SEO report, read into our own — `lib/seo-report.ts`.
 *
 * The fixture is the REAL layout of the first report received (August 2026),
 * run through the real line reader, with the shop's name and domain replaced
 * because this repository is public. Every number in it is as printed.
 *
 * The silent cases come first, because they are the ones nothing else would
 * ever notice: a supplier trace reaching a client, a figure we decided not to
 * repeat leaking into the report anyway, and a section that failed to read
 * disappearing instead of saying so.
 *
 *   npx tsx scripts/check-seo-report.ts
 */
import fixture from './fixtures/seo-report-2026-08.json'
import { parseSeoReport, supplierTraces, type SeoReportInput } from '../src/lib/seo-report'
import { seoSectionOf, senderAllowed, siteAndMonthFromEmail } from '../src/lib/seo-report-inbound'
import { renderMonthlyReportEmail } from '../src/lib/monthly-report-email'
import type { MonthlyDigest } from '../src/lib/monthly-digest'

let failed = 0
function check(label: string, ok: boolean, detail = '') {
  if (!ok) failed++
  console.log(`${ok ? 'ok  ' : 'FAIL'} ${label}${ok || !detail ? '' : ` — ${detail}`}`)
}
const input = fixture as SeoReportInput
const clone = (): SeoReportInput => JSON.parse(JSON.stringify(input))
const report = parseSeoReport(input)

console.log('--- the supplier is never named ---')
{
  check('the real file carries no supplier trace', report.supplierTraces.length === 0, report.supplierTraces.join('; '))
  const producer = clone()
  producer.info = { ...producer.info, Producer: 'BabyLoveGrowth report engine' }
  check('a document field naming them is caught', supplierTraces(producer).length > 0)
  const link = clone()
  link.links = ['https://app.babylovegrowth.ai/reports/123']
  check('a link to any of their hosts is caught', supplierTraces(link).length > 0)
  const text = clone()
  text.pages[4].push('Report generated by babylovegrowth.ai')
  check('their name in the text is caught', supplierTraces(text).length > 0)
}

console.log('\n--- what we decided NOT to repeat stays out ---')
{
  const json = JSON.stringify({ ...report, supplierTraces: [] })
  // Their Google Search figures (a week, not the month), their dollar
  // estimates, and site health.
  for (const figure of ['31,305', '31305', '183', '137.3', '6.7K', '$', 'Meta title', 'Alt text', 'SAVED']) {
    check(`"${figure}" does not appear in what was read`, !json.includes(figure))
  }
  check('the page-1 authority tile (23) is not the rating used', report.links?.ratingTo !== 23)
}

console.log('\n--- a section that cannot be read SAYS so ---')
{
  const noRun = clone()
  noRun.columns[4].left = noRun.columns[4].left.map((l) => l.replace('This run:', 'Latest:'))
  const r = parseSeoReport(noRun)
  check('an unreadable AI sentence drops the AI section', r.ai === null)
  check('and names it in problems', r.problems.some((p) => p.startsWith('AI answers')), r.problems.join('; '))

  const noAi = clone()
  noAi.pages = noAi.pages.slice(0, 4)
  noAi.columns = noAi.columns.slice(0, 4)
  const r2 = parseSeoReport(noAi)
  check('a report with no AI section at all is simply without one', r2.ai === null && !r2.problems.some((p) => p.startsWith('AI')))

  const oneShort = clone()
  oneShort.columns[2].right = oneShort.columns[2].right.filter((l) => !l.startsWith('Aug 4, 2026'))
  const r3 = parseSeoReport(oneShort)
  check('titles and dates that do not pair up drop the LIST', r3.articles?.list.length === 0)
  check('but keep the count', r3.articles?.published === 31)
  check('and say why', r3.problems.some((p) => p.includes('5 titles against 4 dates')), r3.problems.join('; '))

  const noSentence = clone()
  noSentence.columns[3].left = noSentence.columns[3].left.map((l) => l.replace('links across', 'links from'))
  const r5 = parseSeoReport(noSentence)
  check('an unreadable links sentence drops the links section', r5.links === null)
  check('and names it in problems', r5.problems.some((p) => p.startsWith('Links')), r5.problems.join('; '))

  const noDr = clone()
  noDr.columns[3].left = noDr.columns[3].left.filter((l) => !/^DR \d+$/.test(l))
  const r4 = parseSeoReport(noDr)
  check('with no chart values the links still read', r4.links?.links === 35)
  check('and the rating is absent, never guessed', r4.links?.ratingFrom === null && r4.links?.ratingTo === null)
}

console.log('\n--- the real August report ---')
{
  check('site', report.site === 'exampleautoglass.com', String(report.site))
  check('month', report.year === 2026 && report.month === 8, `${report.year}-${report.month}`)
  check('nothing reported as unreadable', report.problems.length === 0, report.problems.join('; '))

  const a = report.articles
  check('31 articles published', a?.published === 31, String(a?.published))
  check('13 visitors from articles', a?.visitors === 13, String(a?.visitors))
  check('five listed by name', a?.list.length === 5, String(a?.list.length))
  check(
    'first one paired with its own date',
    a?.list[0]?.title === 'Classic Car Windshield Replacement in Portland: Same-Day Service' &&
      a?.list[0]?.published === 'Aug 5, 2026',
    JSON.stringify(a?.list[0])
  )
  check(
    'a keyword line is never read as a title',
    !!a?.list.every((x) => !/^[a-z]/.test(x.title))
  )

  const l = report.links
  check('35 links from 21 sites', l?.links === 35 && l?.referringDomains === 21, JSON.stringify(l))
  check('authority 17 → 18 since Jul 2026', l?.ratingFrom === 17 && l?.ratingTo === 18 && l?.since === 'Jul 2026', JSON.stringify(l))
  check('five strongest, strongest first', l?.strongest.length === 5 && l?.strongest[0].domain === 'stacyknows.com' && l?.strongest[0].rating === 41)

  const ai = report.ai
  check('6 of 20 answers, 30%', ai?.named === 6 && ai?.asked === 20 && ai?.share === 30, JSON.stringify(ai))
  check('against 15% in Jul 2026', ai?.previousShare === 15 && ai?.previousLabel === 'Jul 2026')
  check('81 visitors from AI', ai?.visitors === 81, String(ai?.visitors))
  check(
    'by assistant: ChatGPT 40, Claude 20',
    JSON.stringify(ai?.byAssistant) === JSON.stringify([{ name: 'ChatGPT', share: 40 }, { name: 'Claude', share: 20 }]),
    JSON.stringify(ai?.byAssistant)
  )
  check('competitors lead with Safelite 30%', ai?.competitors[0]?.name === 'Safelite' && ai?.competitors[0]?.share === 30)
  check('the shop is never its own competitor', !ai?.competitors.some((c) => /example/i.test(c.name)))
  check(
    'no prompt text fused onto a competitor',
    !!ai?.competitors.every((c) => !/review|what do|best|how to/i.test(c.name)),
    JSON.stringify(ai?.competitors)
  )
}

console.log('\n--- direction is read from the sentence, not the line order ---')
{
  const down = clone()
  down.columns[3].left = down.columns[3].left.map((l) =>
    l.replace('Up 1 point since Jul 2026', 'Down 1 point since Jul 2026')
  )
  const r = parseSeoReport(down)
  check('"Down 1 point" reads 18 → 17', r.links?.ratingFrom === 18 && r.links?.ratingTo === 17, JSON.stringify(r.links))
}

console.log('\n--- who may put a report in front of a client ---')
{
  const owners = { ownerEmails: ['owner@example.com'] }
  check('a stranger is refused', !senderAllowed('someone@example.net', owners).ok)
  check('a look-alike domain is refused', !senderAllowed('team@babylovegrowth.ai.evil.net', owners).ok)
  check('the supplier, via a Gmail filter forward, is accepted', senderAllowed('BLG <team@hey.babylovegrowth.ai>', owners).ok)
  check('the owner forwarding by hand is accepted', senderAllowed('Owner <OWNER@example.com>', owners).ok)
  check(
    'the supplier\'s address failing DMARC is refused',
    !senderAllowed('team@hey.babylovegrowth.ai', { ...owners, authResults: 'mx; spf=fail; dkim=fail; dmarc=fail' }).ok
  )
  check(
    'an SPF fail alone is NOT refused — a Gmail forward always fails SPF',
    senderAllowed('team@hey.babylovegrowth.ai', { ...owners, authResults: 'mx; spf=fail; dkim=pass; dmarc=pass' }).ok
  )
  const fromFile = siteAndMonthFromEmail('Fwd: whatever', 'exampleautoglass.com-2026-08.pdf')
  check('site and month from the file name', fromFile.site === 'exampleautoglass.com' && fromFile.year === 2026 && fromFile.month === 8)
  const fromSubject = siteAndMonthFromEmail('Fwd: www.exampleautoglass.com — SEO report, August 2026', null)
  check('site from a forwarded subject', fromSubject.site === 'exampleautoglass.com', String(fromSubject.site))
}

console.log('\n--- the email carries it honestly ---')
{
  const seo = seoSectionOf(report, new Date('2026-09-01T04:00:00Z'))!
  const hostile = JSON.parse(JSON.stringify(seo))
  hostile.articles.list[0].title = '<script>alert(1)</script> Windshield tips'
  const digest = {
    clientId: 'c1', businessName: 'Example Auto Glass', year: 2026, month: 8, label: 'August 2026',
    timezone: 'America/Los_Angeles', from: '', to: '',
    enquiries: { total: 0, byChannel: { form: 0, phone: 0, sms: 0, other: 0 }, booked: 0, lost: 0, open: 0, revenue: 0 },
    ads: null, work: [], nextSteps: [], note: null, seo: hostile,
  } as MonthlyDigest
  const email = renderMonthlyReportEmail(digest, null)
  check('the SEO section is in the email', email.html.includes('Articles published') && email.text.includes('Named in AI answers: 30%'))
  check('a title out of the PDF is escaped', !email.html.includes('<script>') && email.html.includes('&lt;script&gt;'))
  check(
    'the provenance line no longer claims every figure is the shop\'s own',
    email.html.includes('SEO figures are from our SEO tracking') && !email.html.includes('Every figure here is from your own')
  )
  const without = renderMonthlyReportEmail({ ...digest, seo: null }, null)
  check('and a report without SEO keeps the sentence it always had', without.html.includes('Every figure here is from your own'))
  check('no supplier name in either', !/babylove/i.test(email.html + without.html))
}

console.log(failed === 0 ? '\nALL CASES PASS' : `\n${failed} CASE(S) FAILED`)
process.exit(failed === 0 ? 0 : 1)
